version: '3'
services:
  esphome:
    container_name: esphomebeta
    image: ghcr.io/esphome/esphome:latest
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    environment:
      - USERNAME=${ESPHOME_USERNAME}
      - PASSWORD=${ESPHOME_PASSWORD}
