name: Other Issue
description: Use this template for issues that don't fit into other categories
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Please describe your issue in detail.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the issue here.
