update:
  - platform: http_request
    name: Software Update
    id: update_http_request
    source: https://myesphome.assistantathome.nl/bluetoothproxy/manifest.json



button:
  - platform: template
    id: check_for_update_button
    name: Check for firmware update
    entity_category: diagnostic
    device_class: update
    on_press:
      - component.update: update_http_request
