---
# BluetoothProxy
#
# a simple ESPHome integration to make an bluetoothproxy
# © Maarten Schmeitz
#
substitutions:
  device_name: "bluetoothproxy"
  
esphome:
  name: '${device_name}'
  name_add_mac_suffix: true
  comment: '${device_description}'
  project:
    name: "scns.myESPHome_${device_name}"
    version: "${project_version}"
  min_version: 2026.9.1
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://scns/myESPhome/esphome/bluetoothproxy.yaml

packages:
  bluetoothproxy_update: !include package/bluetoothproxy_update.yaml
  basis_esp32: !include package/basis_esp32.yaml
  bluetoothproxy: !include package/bluetoothproxy.yaml
  basis_settings: !include package/basis_settings.yaml
