---
# vindriktning 
#
# a simple ESPHome integration to make an Kemo M152 to work with Home Assistant 
# © Maarten Schmeitz
#
substitutions:
  device_name: "kemo_m152"
  
esphome:
  name: '${device_name}'
  name_add_mac_suffix: true
  comment: '${device_description}'
  project:
    name: "scns.myESPHome_${device_name}"
    version: "${project_version}"
  min_version: 2026.9.1

esp8266:
  board:  d1_mini
  restore_from_flash: true


dashboard_import:
  package_import_url: github://scns/myESPhome/esphome/kemo_m152.yaml

packages:
  basis_esp8266: !include package/basis_esp8266.yaml
  kemo_m152: !include package/kemo_m152.yaml
  basis_settings: !include package/basis_settings.yaml
